[2025-10-09T00:20:29.550+0000] {processor.py:157} INFO - Started process (PID=43) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:20:29.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:20:29.559+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:20:29.558+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:20:30.940+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:20:30.937+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:20:30.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:20:30.964+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 1.417 seconds
[2025-10-09T00:21:01.113+0000] {processor.py:157} INFO - Started process (PID=114) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:21:01.115+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:21:01.118+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:21:01.118+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:21:01.398+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:21:01.395+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:21:01.398+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:21:01.419+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.309 seconds
[2025-10-09T00:21:31.782+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:21:31.784+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:21:31.788+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:21:31.788+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:21:32.045+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:21:32.043+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:21:32.045+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:21:32.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.285 seconds
[2025-10-09T00:22:02.619+0000] {processor.py:157} INFO - Started process (PID=242) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:22:02.620+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:22:02.623+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:22:02.622+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:22:02.911+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:22:02.908+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:22:02.911+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:22:02.937+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.323 seconds
[2025-10-09T00:22:33.956+0000] {processor.py:157} INFO - Started process (PID=306) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:22:33.958+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:22:33.961+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:22:33.961+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:22:34.234+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:22:34.232+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:22:34.235+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:22:34.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.305 seconds
[2025-10-09T00:23:04.904+0000] {processor.py:157} INFO - Started process (PID=370) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:23:04.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:23:04.909+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:23:04.909+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:23:05.163+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:23:05.161+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:23:05.164+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:23:05.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.283 seconds
[2025-10-09T00:23:35.609+0000] {processor.py:157} INFO - Started process (PID=434) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:23:35.611+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:23:35.613+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:23:35.613+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:23:35.863+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:23:35.861+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:23:35.864+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:23:35.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.279 seconds
[2025-10-09T00:24:05.924+0000] {processor.py:157} INFO - Started process (PID=498) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:24:05.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:24:05.928+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:24:05.928+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:24:06.181+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:24:06.179+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:24:06.182+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:24:06.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.279 seconds
[2025-10-09T00:24:36.271+0000] {processor.py:157} INFO - Started process (PID=562) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:24:36.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:24:36.276+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:24:36.276+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:24:36.508+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:24:36.506+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:24:36.509+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:24:36.526+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.258 seconds
[2025-10-09T00:25:06.616+0000] {processor.py:157} INFO - Started process (PID=626) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:25:06.618+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:25:06.622+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:25:06.622+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:25:06.867+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:25:06.864+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:25:06.867+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:25:06.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.274 seconds
[2025-10-09T00:25:36.974+0000] {processor.py:157} INFO - Started process (PID=691) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:25:36.975+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:25:36.980+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:25:36.979+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:25:37.232+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:25:37.230+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:25:37.232+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:25:37.253+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.283 seconds
[2025-10-09T00:26:07.599+0000] {processor.py:157} INFO - Started process (PID=756) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:26:07.601+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:26:07.602+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:26:07.602+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:26:07.810+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:26:07.809+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:26:07.811+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:26:07.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.230 seconds
[2025-10-09T00:26:38.286+0000] {processor.py:157} INFO - Started process (PID=819) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:26:38.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:26:38.292+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:26:38.291+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:26:38.553+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:26:38.551+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:26:38.553+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:26:38.570+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.287 seconds
[2025-10-09T00:27:08.644+0000] {processor.py:157} INFO - Started process (PID=889) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:27:08.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:27:08.647+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:27:08.647+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:27:08.894+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:27:08.892+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:27:08.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:27:08.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.270 seconds
[2025-10-09T00:27:39.149+0000] {processor.py:157} INFO - Started process (PID=953) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:27:39.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:27:39.153+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:27:39.153+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:27:39.409+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:27:39.407+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:27:39.409+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:27:39.429+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.285 seconds
[2025-10-09T00:28:09.577+0000] {processor.py:157} INFO - Started process (PID=1017) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:28:09.578+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:28:09.582+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:28:09.581+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:28:09.824+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:28:09.822+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:28:09.824+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:28:09.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.268 seconds
[2025-10-09T00:29:21.982+0000] {processor.py:157} INFO - Started process (PID=50) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:29:21.983+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:29:21.986+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:29:21.985+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:29:23.163+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:29:23.158+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:29:23.163+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:29:23.185+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 1.209 seconds
[2025-10-09T00:29:53.217+0000] {processor.py:157} INFO - Started process (PID=114) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:29:53.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:29:53.221+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:29:53.220+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:29:53.459+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:29:53.457+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:29:53.459+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:29:53.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.262 seconds
[2025-10-09T00:30:23.570+0000] {processor.py:157} INFO - Started process (PID=178) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:30:23.572+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:30:23.575+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:30:23.575+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:30:23.792+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:30:23.791+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:30:23.793+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:30:23.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.239 seconds
[2025-10-09T00:30:54.332+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:30:54.333+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:30:54.335+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:30:54.335+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:30:54.614+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:30:54.604+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:30:54.617+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:30:54.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.343 seconds
[2025-10-09T00:31:25.240+0000] {processor.py:157} INFO - Started process (PID=307) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:31:25.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:31:25.244+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:31:25.244+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:31:25.456+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:31:25.454+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:31:25.456+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:31:25.472+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.236 seconds
[2025-10-09T00:31:55.985+0000] {processor.py:157} INFO - Started process (PID=371) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:31:55.986+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:31:55.990+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:31:55.990+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:31:56.228+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:31:56.225+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:31:56.228+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:31:56.244+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.263 seconds
[2025-10-09T00:32:26.806+0000] {processor.py:157} INFO - Started process (PID=435) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:32:26.807+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:32:26.809+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:32:26.808+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:32:27.047+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:32:27.042+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:32:27.047+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:32:27.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.260 seconds
[2025-10-09T00:32:57.797+0000] {processor.py:157} INFO - Started process (PID=499) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:32:57.798+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:32:57.801+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:32:57.800+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:32:58.088+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:32:58.086+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:32:58.090+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:32:58.112+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.319 seconds
[2025-10-09T00:54:36.180+0000] {processor.py:157} INFO - Started process (PID=556) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:54:36.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T00:54:36.185+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:54:36.185+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:54:36.907+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:54:36.900+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:54:36.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T00:54:36.956+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.781 seconds
[2025-10-09T03:52:02.430+0000] {processor.py:157} INFO - Started process (PID=620) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T03:52:02.432+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T03:52:02.437+0000] {logging_mixin.py:151} INFO - [2025-10-09T03:52:02.436+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T03:52:02.933+0000] {logging_mixin.py:151} INFO - [2025-10-09T03:52:02.927+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T03:52:02.935+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T03:52:02.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.554 seconds
[2025-10-09T04:16:14.325+0000] {processor.py:157} INFO - Started process (PID=684) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T04:16:14.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T04:16:14.333+0000] {logging_mixin.py:151} INFO - [2025-10-09T04:16:14.332+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T04:16:14.783+0000] {logging_mixin.py:151} INFO - [2025-10-09T04:16:14.780+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T04:16:14.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T04:16:14.806+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.488 seconds
[2025-10-09T04:49:47.102+0000] {processor.py:157} INFO - Started process (PID=748) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T04:49:47.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T04:49:47.123+0000] {logging_mixin.py:151} INFO - [2025-10-09T04:49:47.121+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T04:49:47.637+0000] {logging_mixin.py:151} INFO - [2025-10-09T04:49:47.634+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T04:49:47.638+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T04:49:47.669+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.585 seconds
[2025-10-09T05:08:06.332+0000] {processor.py:157} INFO - Started process (PID=812) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:08:06.333+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:08:06.336+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:08:06.336+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:08:06.698+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:08:06.692+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:08:06.699+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:08:06.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.389 seconds
[2025-10-09T05:50:39.993+0000] {processor.py:157} INFO - Started process (PID=876) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:50:40.007+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:50:40.015+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:50:40.014+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:50:40.761+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:50:40.755+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:50:40.762+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:50:40.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.805 seconds
[2025-10-09T05:51:11.468+0000] {processor.py:157} INFO - Started process (PID=940) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:51:11.471+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:51:11.484+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:51:11.484+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:51:11.884+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:51:11.880+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:51:11.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:51:11.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.451 seconds
[2025-10-09T05:51:42.580+0000] {processor.py:157} INFO - Started process (PID=1004) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:51:42.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:51:42.587+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:51:42.586+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:51:42.930+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:51:42.923+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:51:42.931+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:51:42.977+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.402 seconds
[2025-10-09T05:52:13.946+0000] {processor.py:157} INFO - Started process (PID=1068) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:52:13.950+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:52:13.951+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:52:13.951+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:52:14.222+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:52:14.220+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:52:14.223+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:52:14.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.298 seconds
[2025-10-09T05:52:45.025+0000] {processor.py:157} INFO - Started process (PID=1132) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:52:45.031+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:52:45.072+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:52:45.060+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:52:45.631+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:52:45.628+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:52:45.632+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:52:45.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.649 seconds
[2025-10-09T05:53:16.189+0000] {processor.py:157} INFO - Started process (PID=1196) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:53:16.192+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:53:16.209+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:53:16.209+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:53:16.725+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:53:16.722+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:53:16.728+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:53:16.759+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.579 seconds
[2025-10-09T05:53:47.600+0000] {processor.py:157} INFO - Started process (PID=1260) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:53:47.602+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:53:47.609+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:53:47.609+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:53:47.942+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:53:47.940+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:53:47.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:53:47.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.370 seconds
[2025-10-09T05:54:18.342+0000] {processor.py:157} INFO - Started process (PID=1324) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:54:18.346+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:54:18.354+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:54:18.353+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:54:18.739+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:54:18.735+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:54:18.739+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:54:18.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.439 seconds
[2025-10-09T05:54:48.919+0000] {processor.py:157} INFO - Started process (PID=1388) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:54:48.922+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:54:48.925+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:54:48.925+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:54:49.264+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:54:49.255+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:54:49.267+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:54:49.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.459 seconds
[2025-10-09T05:55:20.252+0000] {processor.py:157} INFO - Started process (PID=1452) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:55:20.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:55:20.258+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:55:20.257+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:55:20.487+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:55:20.485+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:55:20.488+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:55:20.508+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.259 seconds
[2025-10-09T05:55:50.545+0000] {processor.py:157} INFO - Started process (PID=1516) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:55:50.546+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:55:50.549+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:55:50.548+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:55:50.819+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:55:50.817+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:55:50.819+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:55:50.834+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.292 seconds
[2025-10-09T05:56:20.880+0000] {processor.py:157} INFO - Started process (PID=1580) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:56:20.882+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:56:20.884+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:56:20.884+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:56:21.154+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:56:21.151+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:56:21.154+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:56:21.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.298 seconds
[2025-10-09T05:56:51.279+0000] {processor.py:157} INFO - Started process (PID=1644) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:56:51.281+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:56:51.283+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:56:51.283+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:56:51.550+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:56:51.547+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:56:51.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:56:51.567+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.291 seconds
[2025-10-09T05:57:22.544+0000] {processor.py:157} INFO - Started process (PID=1708) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:57:22.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:57:22.547+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:57:22.546+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:57:22.823+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:57:22.821+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:57:22.825+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:57:22.841+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.300 seconds
[2025-10-09T05:57:53.009+0000] {processor.py:157} INFO - Started process (PID=1772) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:57:53.010+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:57:53.012+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:57:53.012+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:57:53.298+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:57:53.294+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:57:53.299+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:57:53.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.323 seconds
[2025-10-09T05:58:23.714+0000] {processor.py:157} INFO - Started process (PID=1836) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:58:23.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:58:23.727+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:58:23.726+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:58:24.094+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:58:24.091+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:58:24.094+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:58:24.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.402 seconds
[2025-10-09T05:58:54.277+0000] {processor.py:157} INFO - Started process (PID=1900) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:58:54.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:58:54.284+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:58:54.284+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:58:54.570+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:58:54.562+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:58:54.570+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:58:54.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.321 seconds
[2025-10-09T05:59:25.581+0000] {processor.py:157} INFO - Started process (PID=1964) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:59:25.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:59:25.588+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:59:25.587+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:59:25.882+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:59:25.878+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:59:25.882+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:59:25.909+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.332 seconds
[2025-10-09T05:59:56.061+0000] {processor.py:157} INFO - Started process (PID=2028) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:59:56.062+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T05:59:56.064+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:59:56.063+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:59:56.341+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:59:56.339+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:59:56.342+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T05:59:56.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.301 seconds
[2025-10-09T06:00:27.361+0000] {processor.py:157} INFO - Started process (PID=2092) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:00:27.365+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:00:27.368+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:00:27.368+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:00:27.668+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:00:27.666+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:00:27.669+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:00:27.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.333 seconds
[2025-10-09T06:00:58.176+0000] {processor.py:157} INFO - Started process (PID=2156) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:00:58.178+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:00:58.180+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:00:58.180+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:00:58.460+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:00:58.458+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:00:58.461+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:00:58.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.306 seconds
[2025-10-09T06:01:29.097+0000] {processor.py:157} INFO - Started process (PID=2220) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:01:29.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:01:29.100+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:01:29.100+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:01:29.617+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:01:29.606+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:01:29.619+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:01:29.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.581 seconds
[2025-10-09T06:01:59.810+0000] {processor.py:157} INFO - Started process (PID=2284) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:01:59.812+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:01:59.817+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:01:59.816+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:02:00.253+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:02:00.250+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:02:00.253+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:02:00.271+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.467 seconds
[2025-10-09T06:02:30.599+0000] {processor.py:157} INFO - Started process (PID=2347) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:02:30.600+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:02:30.606+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:02:30.605+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:02:30.863+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:02:30.861+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:02:30.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:02:30.884+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.288 seconds
[2025-10-09T06:03:01.878+0000] {processor.py:157} INFO - Started process (PID=2411) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:03:01.879+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:03:01.882+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:03:01.882+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:03:02.141+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:03:02.139+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:03:02.142+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:03:02.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.290 seconds
[2025-10-09T06:03:32.220+0000] {processor.py:157} INFO - Started process (PID=2482) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:03:32.224+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:03:32.226+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:03:32.225+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:03:32.502+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:03:32.500+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:03:32.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:03:32.522+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.305 seconds
[2025-10-09T06:04:02.922+0000] {processor.py:157} INFO - Started process (PID=2546) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:04:02.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:04:02.930+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:04:02.929+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:04:03.682+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:04:03.673+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:04:03.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:04:03.744+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.829 seconds
[2025-10-09T06:04:34.456+0000] {processor.py:157} INFO - Started process (PID=2610) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:04:34.459+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:04:34.463+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:04:34.463+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:04:34.750+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:04:34.748+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:04:34.750+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:04:34.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.317 seconds
[2025-10-09T06:05:05.782+0000] {processor.py:157} INFO - Started process (PID=2674) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:05:05.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:05:05.785+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:05:05.785+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:05:06.047+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:05:06.044+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:05:06.047+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:05:06.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.285 seconds
[2025-10-09T06:05:36.216+0000] {processor.py:157} INFO - Started process (PID=2738) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:05:36.217+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:05:36.219+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:05:36.219+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:05:36.515+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:05:36.513+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:05:36.515+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:05:36.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.322 seconds
[2025-10-09T06:06:06.836+0000] {processor.py:157} INFO - Started process (PID=2802) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:06:06.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:06:06.842+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:06:06.841+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:06:07.164+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:06:07.161+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:06:07.164+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:06:07.184+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.353 seconds
[2025-10-09T06:06:37.975+0000] {processor.py:157} INFO - Started process (PID=2866) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:06:37.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:06:37.980+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:06:37.979+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:06:38.239+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:06:38.237+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:06:38.239+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:06:38.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.283 seconds
[2025-10-09T06:07:08.691+0000] {processor.py:157} INFO - Started process (PID=2930) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:07:08.693+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:07:08.695+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:07:08.695+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:07:08.904+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:07:08.902+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:07:08.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:07:08.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.228 seconds
[2025-10-09T06:07:39.939+0000] {processor.py:157} INFO - Started process (PID=2994) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:07:39.941+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:07:39.944+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:07:39.943+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:07:40.198+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:07:40.195+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:07:40.198+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:07:40.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.281 seconds
[2025-10-09T06:08:10.322+0000] {processor.py:157} INFO - Started process (PID=3058) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:08:10.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:08:10.325+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:08:10.325+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:08:10.548+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:08:10.546+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:08:10.548+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:08:10.565+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.246 seconds
[2025-10-09T06:08:40.604+0000] {processor.py:157} INFO - Started process (PID=3122) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:08:40.607+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:08:40.610+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:08:40.610+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:08:40.864+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:08:40.861+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:08:40.865+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:08:40.882+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.281 seconds
[2025-10-09T06:09:11.842+0000] {processor.py:157} INFO - Started process (PID=3186) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:09:11.844+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:09:11.847+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:09:11.847+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:09:12.191+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:09:12.189+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:09:12.191+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:09:12.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.367 seconds
[2025-10-09T06:09:42.446+0000] {processor.py:157} INFO - Started process (PID=3250) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:09:42.447+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:09:42.451+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:09:42.451+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:09:42.707+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:09:42.705+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:09:42.708+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:09:42.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.283 seconds
[2025-10-09T06:10:12.988+0000] {processor.py:157} INFO - Started process (PID=3314) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:10:12.990+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:10:12.992+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:10:12.992+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:10:13.274+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:10:13.269+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:10:13.274+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:10:13.297+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.312 seconds
[2025-10-09T06:10:43.465+0000] {processor.py:157} INFO - Started process (PID=3378) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:10:43.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:10:43.467+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:10:43.467+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:10:43.682+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:10:43.681+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:10:43.683+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:10:43.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.237 seconds
[2025-10-09T06:11:13.747+0000] {processor.py:157} INFO - Started process (PID=3442) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:11:13.748+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:11:13.751+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:11:13.751+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:11:14.192+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:11:14.190+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:11:14.192+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:11:14.206+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.461 seconds
[2025-10-09T06:11:44.266+0000] {processor.py:157} INFO - Started process (PID=3506) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:11:44.268+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:11:44.270+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:11:44.270+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:11:44.545+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:11:44.542+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:11:44.545+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:11:44.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.416 seconds
[2025-10-09T06:27:57.745+0000] {processor.py:157} INFO - Started process (PID=3570) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:27:57.752+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:27:57.766+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:27:57.765+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:27:58.594+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:27:58.590+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:27:58.595+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:27:58.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.884 seconds
[2025-10-09T06:35:26.885+0000] {processor.py:157} INFO - Started process (PID=3634) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:35:26.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:35:26.889+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:35:26.889+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:35:27.854+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:35:27.826+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:35:27.873+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:35:27.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 1.042 seconds
[2025-10-09T06:59:38.148+0000] {processor.py:157} INFO - Started process (PID=3698) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:59:38.150+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T06:59:38.161+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:59:38.161+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:59:39.846+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:59:39.843+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:59:39.846+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T06:59:39.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 1.737 seconds
[2025-10-09T07:16:09.766+0000] {processor.py:157} INFO - Started process (PID=3762) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:16:09.767+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:16:09.769+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:16:09.768+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:16:10.517+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:16:10.515+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:16:10.517+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:16:10.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.777 seconds
[2025-10-09T07:16:41.363+0000] {processor.py:157} INFO - Started process (PID=3826) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:16:41.363+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:16:41.365+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:16:41.365+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:16:41.722+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:16:41.721+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:16:41.723+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:16:41.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.377 seconds
[2025-10-09T07:17:48.009+0000] {processor.py:157} INFO - Started process (PID=3890) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:17:48.010+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:17:48.012+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:17:48.012+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:17:48.378+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:17:48.376+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:17:48.378+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:17:48.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.383 seconds
[2025-10-09T07:18:19.379+0000] {processor.py:157} INFO - Started process (PID=3954) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:18:19.382+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:18:19.386+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:18:19.385+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:18:19.878+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:18:19.875+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:18:19.878+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:18:19.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.518 seconds
[2025-10-09T07:19:19.769+0000] {processor.py:157} INFO - Started process (PID=4018) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:19:19.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:19:19.773+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:19:19.772+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:19:20.144+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:19:20.142+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:19:20.144+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:19:20.156+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.389 seconds
[2025-10-09T07:21:37.264+0000] {processor.py:157} INFO - Started process (PID=4082) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:21:37.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:21:37.271+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:21:37.271+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:21:37.779+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:21:37.775+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:21:37.780+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:21:37.794+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.537 seconds
[2025-10-09T07:22:22.176+0000] {processor.py:157} INFO - Started process (PID=4146) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:22:22.177+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:22:22.181+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:22:22.180+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:22:22.542+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:22:22.539+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:22:22.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:22:22.555+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.382 seconds
[2025-10-09T07:23:10.790+0000] {processor.py:157} INFO - Started process (PID=4210) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:23:10.792+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:23:10.796+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:23:10.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:23:11.166+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:23:11.164+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:23:11.166+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:23:11.178+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.397 seconds
[2025-10-09T07:24:31.057+0000] {processor.py:157} INFO - Started process (PID=4274) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:24:31.059+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:24:31.062+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:24:31.062+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:24:31.397+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:24:31.396+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:24:31.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:24:31.411+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.356 seconds
[2025-10-09T07:25:03.290+0000] {processor.py:157} INFO - Started process (PID=4338) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:25:03.291+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:25:03.292+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:25:03.292+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:25:03.658+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:25:03.655+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:25:03.659+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:25:03.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.387 seconds
[2025-10-09T07:25:34.073+0000] {processor.py:157} INFO - Started process (PID=4402) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:25:34.074+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:25:34.076+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:25:34.075+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:25:34.501+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:25:34.497+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:25:34.502+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:25:34.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.444 seconds
[2025-10-09T07:27:18.542+0000] {processor.py:157} INFO - Started process (PID=4466) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:27:18.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:27:18.544+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:27:18.544+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:27:18.910+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:27:18.908+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:27:18.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:27:18.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.382 seconds
[2025-10-09T07:28:31.609+0000] {processor.py:157} INFO - Started process (PID=4530) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:28:31.610+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:28:31.612+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:28:31.612+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:28:32.173+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:28:32.172+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:28:32.174+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:28:32.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.585 seconds
[2025-10-09T07:29:17.521+0000] {processor.py:157} INFO - Started process (PID=4594) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:29:17.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:29:17.526+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:29:17.526+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:29:18.064+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:29:18.062+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:29:18.064+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:29:18.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.564 seconds
[2025-10-09T07:30:33.751+0000] {processor.py:157} INFO - Started process (PID=4658) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:30:33.752+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:30:33.756+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:30:33.756+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:30:34.188+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:30:34.187+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:30:34.189+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:30:34.201+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.455 seconds
[2025-10-09T07:32:34.477+0000] {processor.py:157} INFO - Started process (PID=4722) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:32:34.479+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:32:34.481+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:32:34.481+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:32:34.825+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:32:34.824+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:32:34.826+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:32:34.839+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.365 seconds
[2025-10-09T07:33:06.169+0000] {processor.py:157} INFO - Started process (PID=4786) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:33:06.170+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:33:06.172+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:33:06.172+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:33:06.541+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:33:06.539+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:33:06.541+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:33:06.556+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.390 seconds
[2025-10-09T07:34:35.535+0000] {processor.py:157} INFO - Started process (PID=4850) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:34:35.536+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:34:35.538+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:34:35.538+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:34:35.899+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:34:35.898+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:34:35.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:34:35.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.382 seconds
[2025-10-09T07:35:07.778+0000] {processor.py:157} INFO - Started process (PID=4914) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:35:07.779+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T07:35:07.780+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:35:07.780+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:35:08.151+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:35:08.150+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:35:08.152+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T07:35:08.166+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.392 seconds
[2025-10-09T08:05:48.150+0000] {processor.py:157} INFO - Started process (PID=4978) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:05:48.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T08:05:48.156+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:05:48.155+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:05:48.969+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:05:48.967+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T08:05:48.970+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:05:49.001+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.856 seconds
[2025-10-09T08:30:29.779+0000] {processor.py:157} INFO - Started process (PID=5042) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:30:29.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T08:30:29.789+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:30:29.788+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:30:30.664+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:30:30.662+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T08:30:30.665+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:30:30.683+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.915 seconds
[2025-10-09T08:46:52.016+0000] {processor.py:157} INFO - Started process (PID=5106) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:46:52.017+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T08:46:52.021+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:46:52.021+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:46:52.720+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:46:52.717+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T08:46:52.720+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T08:46:52.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.725 seconds
[2025-10-09T09:57:04.218+0000] {processor.py:157} INFO - Started process (PID=5170) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T09:57:04.220+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T09:57:04.222+0000] {logging_mixin.py:151} INFO - [2025-10-09T09:57:04.222+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T09:57:04.714+0000] {logging_mixin.py:151} INFO - [2025-10-09T09:57:04.711+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T09:57:04.714+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T09:57:04.735+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.524 seconds
[2025-10-09T11:25:22.086+0000] {processor.py:157} INFO - Started process (PID=5234) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T11:25:22.089+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T11:25:22.093+0000] {logging_mixin.py:151} INFO - [2025-10-09T11:25:22.092+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T11:25:22.763+0000] {logging_mixin.py:151} INFO - [2025-10-09T11:25:22.762+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T11:25:22.763+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T11:25:22.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.697 seconds
[2025-10-09T12:36:32.331+0000] {processor.py:157} INFO - Started process (PID=5298) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T12:36:32.333+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T12:36:32.338+0000] {logging_mixin.py:151} INFO - [2025-10-09T12:36:32.337+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T12:36:33.429+0000] {logging_mixin.py:151} INFO - [2025-10-09T12:36:33.419+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T12:36:33.431+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T12:36:33.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 1.136 seconds
[2025-10-09T12:37:04.230+0000] {processor.py:157} INFO - Started process (PID=5362) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T12:37:04.231+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T12:37:04.234+0000] {logging_mixin.py:151} INFO - [2025-10-09T12:37:04.234+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T12:37:04.678+0000] {logging_mixin.py:151} INFO - [2025-10-09T12:37:04.673+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T12:37:04.679+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T12:37:04.691+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.467 seconds
[2025-10-09T14:05:26.786+0000] {processor.py:157} INFO - Started process (PID=5426) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T14:05:26.787+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T14:05:26.792+0000] {logging_mixin.py:151} INFO - [2025-10-09T14:05:26.791+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T14:05:27.296+0000] {logging_mixin.py:151} INFO - [2025-10-09T14:05:27.294+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T14:05:27.298+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T14:05:27.314+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.532 seconds
[2025-10-09T14:24:34.425+0000] {processor.py:157} INFO - Started process (PID=5490) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T14:24:34.427+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T14:24:34.431+0000] {logging_mixin.py:151} INFO - [2025-10-09T14:24:34.431+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T14:24:35.170+0000] {logging_mixin.py:151} INFO - [2025-10-09T14:24:35.150+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T14:24:35.172+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T14:24:35.246+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.825 seconds
[2025-10-09T15:06:47.305+0000] {processor.py:157} INFO - Started process (PID=5554) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:06:47.306+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T15:06:47.307+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:06:47.307+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:06:47.723+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:06:47.718+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:06:47.724+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:06:47.760+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.458 seconds
[2025-10-09T15:49:10.692+0000] {processor.py:157} INFO - Started process (PID=5618) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:49:10.694+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T15:49:10.698+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:49:10.698+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:49:11.492+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:49:11.489+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:49:11.494+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:49:11.512+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.825 seconds
[2025-10-09T15:49:42.053+0000] {processor.py:157} INFO - Started process (PID=5682) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:49:42.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T15:49:42.056+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:49:42.056+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:49:42.469+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:49:42.466+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:49:42.469+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:49:42.486+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.438 seconds
[2025-10-09T15:50:12.568+0000] {processor.py:157} INFO - Started process (PID=5746) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:50:12.569+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T15:50:12.572+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:50:12.572+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:50:12.897+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:50:12.896+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:50:12.897+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:50:12.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.347 seconds
[2025-10-09T15:50:43.312+0000] {processor.py:157} INFO - Started process (PID=5811) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:50:43.313+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T15:50:43.318+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:50:43.317+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:50:43.626+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:50:43.624+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:50:43.626+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T15:50:43.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.332 seconds
[2025-10-09T16:07:40.914+0000] {processor.py:157} INFO - Started process (PID=5874) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:07:40.918+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T16:07:40.924+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:07:40.924+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:07:41.948+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:07:41.945+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:07:41.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:07:41.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 1.080 seconds
[2025-10-09T16:19:53.800+0000] {processor.py:157} INFO - Started process (PID=5938) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:19:53.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T16:19:53.804+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:19:53.804+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:19:54.267+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:19:54.263+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:19:54.267+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:19:54.283+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.488 seconds
[2025-10-09T16:20:25.040+0000] {processor.py:157} INFO - Started process (PID=6002) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:20:25.041+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T16:20:25.043+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:20:25.043+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:20:25.762+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:20:25.760+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:20:25.763+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:20:25.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.754 seconds
[2025-10-09T16:20:56.249+0000] {processor.py:157} INFO - Started process (PID=6066) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:20:56.250+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T16:20:56.252+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:20:56.251+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:20:56.794+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:20:56.792+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:20:56.794+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:20:56.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.562 seconds
[2025-10-09T16:21:27.314+0000] {processor.py:157} INFO - Started process (PID=6130) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:21:27.315+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T16:21:27.319+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:21:27.318+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:21:28.668+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:21:28.665+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:21:28.668+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:21:28.693+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 1.382 seconds
[2025-10-09T16:21:58.878+0000] {processor.py:157} INFO - Started process (PID=6194) to work on /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:21:58.879+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/evaluate_model.py for tasks to queue
[2025-10-09T16:21:58.882+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:21:58.882+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:21:59.325+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:21:59.324+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/evaluate_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/evaluate_model.py", line 3, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:21:59.326+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/evaluate_model.py
[2025-10-09T16:21:59.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/evaluate_model.py took 0.467 seconds
