[2025-10-09T00:20:30.992+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:20:30.993+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:20:30.995+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:20:30.995+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:20:31.242+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:20:31.240+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:20:31.243+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:20:31.268+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.280 seconds
[2025-10-09T00:21:01.434+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:21:01.434+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:21:01.436+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:21:01.436+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:21:01.648+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:21:01.647+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:21:01.649+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:21:01.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.231 seconds
[2025-10-09T00:21:32.076+0000] {processor.py:157} INFO - Started process (PID=181) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:21:32.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:21:32.078+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:21:32.078+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:21:32.276+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:21:32.275+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:21:32.277+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:21:32.291+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.217 seconds
[2025-10-09T00:22:02.950+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:22:02.951+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:22:02.953+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:22:02.953+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:22:03.160+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:22:03.158+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:22:03.161+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:22:03.177+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.228 seconds
[2025-10-09T00:22:34.272+0000] {processor.py:157} INFO - Started process (PID=309) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:22:34.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:22:34.274+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:22:34.273+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:22:34.747+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:22:34.745+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:22:34.747+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:22:34.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.498 seconds
[2025-10-09T00:23:05.201+0000] {processor.py:157} INFO - Started process (PID=373) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:23:05.202+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:23:05.203+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:23:05.203+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:23:05.410+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:23:05.408+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:23:05.410+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:23:05.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.226 seconds
[2025-10-09T00:23:35.901+0000] {processor.py:157} INFO - Started process (PID=437) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:23:35.902+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:23:35.904+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:23:35.903+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:23:36.109+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:23:36.108+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:23:36.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:23:36.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.227 seconds
[2025-10-09T00:24:06.213+0000] {processor.py:157} INFO - Started process (PID=501) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:24:06.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:24:06.215+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:24:06.215+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:24:06.411+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:24:06.409+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:24:06.411+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:24:06.425+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.214 seconds
[2025-10-09T00:24:36.541+0000] {processor.py:157} INFO - Started process (PID=565) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:24:36.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:24:36.544+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:24:36.544+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:24:36.754+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:24:36.752+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:24:36.754+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:24:36.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.230 seconds
[2025-10-09T00:25:06.900+0000] {processor.py:157} INFO - Started process (PID=629) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:25:06.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:25:06.902+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:25:06.901+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:25:07.140+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:25:07.139+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:25:07.141+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:25:07.155+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.258 seconds
[2025-10-09T00:25:37.267+0000] {processor.py:157} INFO - Started process (PID=694) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:25:37.269+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:25:37.273+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:25:37.273+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:25:37.500+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:25:37.498+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:25:37.501+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:25:37.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.253 seconds
[2025-10-09T00:26:07.600+0000] {processor.py:157} INFO - Started process (PID=757) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:26:07.601+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:26:07.603+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:26:07.603+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:26:07.810+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:26:07.809+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:26:07.811+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:26:07.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.229 seconds
[2025-10-09T00:26:38.588+0000] {processor.py:157} INFO - Started process (PID=822) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:26:38.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:26:38.591+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:26:38.591+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:26:38.839+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:26:38.837+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:26:38.839+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:26:38.854+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.269 seconds
[2025-10-09T00:27:08.926+0000] {processor.py:157} INFO - Started process (PID=892) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:27:08.927+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:27:08.928+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:27:08.928+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:27:09.128+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:27:09.127+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:27:09.129+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:27:09.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.217 seconds
[2025-10-09T00:27:39.447+0000] {processor.py:157} INFO - Started process (PID=956) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:27:39.448+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:27:39.450+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:27:39.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:27:39.676+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:27:39.674+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:27:39.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:27:39.690+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.246 seconds
[2025-10-09T00:28:09.856+0000] {processor.py:157} INFO - Started process (PID=1020) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:28:09.857+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:28:09.858+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:28:09.858+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:28:10.063+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:28:10.061+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:28:10.064+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:28:10.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.225 seconds
[2025-10-09T00:29:23.206+0000] {processor.py:157} INFO - Started process (PID=54) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:29:23.207+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:29:23.209+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:29:23.209+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:29:23.448+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:29:23.447+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:29:23.449+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:29:23.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.260 seconds
[2025-10-09T00:29:53.493+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:29:53.494+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:29:53.496+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:29:53.496+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:29:53.710+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:29:53.708+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:29:53.710+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:29:53.723+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.233 seconds
[2025-10-09T00:30:23.828+0000] {processor.py:157} INFO - Started process (PID=181) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:30:23.830+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:30:23.832+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:30:23.832+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:30:24.047+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:30:24.045+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:30:24.047+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:30:24.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.237 seconds
[2025-10-09T00:30:54.729+0000] {processor.py:157} INFO - Started process (PID=246) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:30:54.731+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:30:54.737+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:30:54.736+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:30:55.018+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:30:55.016+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:30:55.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:30:55.037+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.316 seconds
[2025-10-09T00:31:25.487+0000] {processor.py:157} INFO - Started process (PID=310) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:31:25.488+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:31:25.489+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:31:25.489+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:31:25.689+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:31:25.687+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:31:25.689+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:31:25.704+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.220 seconds
[2025-10-09T00:31:56.259+0000] {processor.py:157} INFO - Started process (PID=374) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:31:56.260+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:31:56.261+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:31:56.261+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:31:56.461+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:31:56.459+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:31:56.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:31:56.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.221 seconds
[2025-10-09T00:32:27.078+0000] {processor.py:157} INFO - Started process (PID=438) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:32:27.079+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:32:27.080+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:32:27.080+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:32:27.283+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:32:27.281+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:32:27.283+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:32:27.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.219 seconds
[2025-10-09T00:32:58.128+0000] {processor.py:157} INFO - Started process (PID=502) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:32:58.129+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:32:58.130+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:32:58.130+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:32:58.338+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:32:58.336+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:32:58.338+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:32:58.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.227 seconds
[2025-10-09T00:54:36.991+0000] {processor.py:157} INFO - Started process (PID=559) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T00:54:36.992+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T00:54:36.996+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:54:36.995+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:54:37.292+0000] {logging_mixin.py:151} INFO - [2025-10-09T00:54:37.290+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T00:54:37.293+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T00:54:37.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.323 seconds
[2025-10-09T03:52:03.012+0000] {processor.py:157} INFO - Started process (PID=623) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T03:52:03.013+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T03:52:03.017+0000] {logging_mixin.py:151} INFO - [2025-10-09T03:52:03.017+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T03:52:03.342+0000] {logging_mixin.py:151} INFO - [2025-10-09T03:52:03.339+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T03:52:03.345+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T03:52:03.365+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.358 seconds
[2025-10-09T04:16:14.846+0000] {processor.py:157} INFO - Started process (PID=687) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T04:16:14.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T04:16:14.851+0000] {logging_mixin.py:151} INFO - [2025-10-09T04:16:14.850+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T04:16:15.130+0000] {logging_mixin.py:151} INFO - [2025-10-09T04:16:15.126+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T04:16:15.131+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T04:16:15.144+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.304 seconds
[2025-10-09T04:49:47.699+0000] {processor.py:157} INFO - Started process (PID=751) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T04:49:47.700+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T04:49:47.702+0000] {logging_mixin.py:151} INFO - [2025-10-09T04:49:47.701+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T04:49:47.930+0000] {logging_mixin.py:151} INFO - [2025-10-09T04:49:47.928+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T04:49:47.930+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T04:49:47.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.248 seconds
[2025-10-09T05:08:06.735+0000] {processor.py:157} INFO - Started process (PID=815) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:08:06.738+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:08:06.742+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:08:06.742+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:08:06.977+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:08:06.974+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:08:06.978+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:08:06.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.262 seconds
[2025-10-09T05:50:40.811+0000] {processor.py:157} INFO - Started process (PID=879) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:50:40.816+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:50:40.818+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:50:40.817+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:50:41.075+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:50:41.072+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:50:41.075+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:50:41.088+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.280 seconds
[2025-10-09T05:51:11.937+0000] {processor.py:157} INFO - Started process (PID=943) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:51:11.939+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:51:11.942+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:51:11.942+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:51:12.225+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:51:12.221+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:51:12.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:51:12.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.313 seconds
[2025-10-09T05:51:43.044+0000] {processor.py:157} INFO - Started process (PID=1007) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:51:43.046+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:51:43.050+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:51:43.049+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:51:43.405+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:51:43.402+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:51:43.406+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:51:43.424+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.390 seconds
[2025-10-09T05:52:14.256+0000] {processor.py:157} INFO - Started process (PID=1071) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:52:14.257+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:52:14.259+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:52:14.258+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:52:14.464+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:52:14.462+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:52:14.464+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:52:14.476+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.222 seconds
[2025-10-09T05:52:45.682+0000] {processor.py:157} INFO - Started process (PID=1135) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:52:45.683+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:52:45.685+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:52:45.684+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:52:45.976+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:52:45.974+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:52:45.977+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:52:45.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.315 seconds
[2025-10-09T05:53:16.783+0000] {processor.py:157} INFO - Started process (PID=1199) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:53:16.784+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:53:16.787+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:53:16.787+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:53:17.143+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:53:17.140+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:53:17.144+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:53:17.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.387 seconds
[2025-10-09T05:53:47.985+0000] {processor.py:157} INFO - Started process (PID=1263) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:53:47.987+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:53:47.989+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:53:47.989+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:53:48.222+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:53:48.218+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:53:48.223+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:53:48.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.257 seconds
[2025-10-09T05:54:18.800+0000] {processor.py:157} INFO - Started process (PID=1327) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:54:18.801+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:54:18.805+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:54:18.804+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:54:19.042+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:54:19.040+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:54:19.042+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:54:19.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.262 seconds
[2025-10-09T05:54:49.475+0000] {processor.py:157} INFO - Started process (PID=1391) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:54:49.478+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:54:49.483+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:54:49.482+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:54:49.791+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:54:49.789+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:54:49.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:54:49.804+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.334 seconds
[2025-10-09T05:55:20.520+0000] {processor.py:157} INFO - Started process (PID=1455) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:55:20.522+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:55:20.526+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:55:20.526+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:55:20.748+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:55:20.746+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:55:20.750+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:55:20.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.249 seconds
[2025-10-09T05:55:50.855+0000] {processor.py:157} INFO - Started process (PID=1519) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:55:50.856+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:55:50.857+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:55:50.857+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:55:51.098+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:55:51.096+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:55:51.098+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:55:51.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.259 seconds
[2025-10-09T05:56:21.191+0000] {processor.py:157} INFO - Started process (PID=1583) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:56:21.192+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:56:21.194+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:56:21.194+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:56:21.400+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:56:21.398+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:56:21.401+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:56:21.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.228 seconds
[2025-10-09T05:56:51.584+0000] {processor.py:157} INFO - Started process (PID=1647) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:56:51.585+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:56:51.586+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:56:51.586+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:56:51.803+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:56:51.801+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:56:51.804+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:56:51.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.236 seconds
[2025-10-09T05:57:22.864+0000] {processor.py:157} INFO - Started process (PID=1711) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:57:22.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:57:22.867+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:57:22.867+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:57:23.100+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:57:23.097+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:57:23.100+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:57:23.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.256 seconds
[2025-10-09T05:57:53.350+0000] {processor.py:157} INFO - Started process (PID=1775) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:57:53.351+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:57:53.353+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:57:53.353+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:57:53.616+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:57:53.613+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:57:53.616+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:57:53.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.291 seconds
[2025-10-09T05:58:24.134+0000] {processor.py:157} INFO - Started process (PID=1839) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:58:24.135+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:58:24.139+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:58:24.139+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:58:24.363+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:58:24.358+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:58:24.363+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:58:24.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.245 seconds
[2025-10-09T05:58:54.611+0000] {processor.py:157} INFO - Started process (PID=1903) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:58:54.615+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:58:54.617+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:58:54.617+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:58:54.867+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:58:54.865+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:58:54.868+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:58:54.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.282 seconds
[2025-10-09T05:59:25.927+0000] {processor.py:157} INFO - Started process (PID=1967) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:59:25.929+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:59:25.931+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:59:25.931+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:59:26.195+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:59:26.193+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:59:26.196+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:59:26.211+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.287 seconds
[2025-10-09T05:59:56.375+0000] {processor.py:157} INFO - Started process (PID=2031) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T05:59:56.375+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T05:59:56.377+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:59:56.376+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:59:56.593+0000] {logging_mixin.py:151} INFO - [2025-10-09T05:59:56.592+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T05:59:56.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T05:59:56.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.234 seconds
[2025-10-09T06:00:27.710+0000] {processor.py:157} INFO - Started process (PID=2095) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:00:27.711+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:00:27.713+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:00:27.713+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:00:28.007+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:00:28.004+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:00:28.007+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:00:28.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.320 seconds
[2025-10-09T06:00:58.501+0000] {processor.py:157} INFO - Started process (PID=2159) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:00:58.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:00:58.505+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:00:58.505+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:00:58.737+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:00:58.735+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:00:58.737+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:00:58.750+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.251 seconds
[2025-10-09T06:01:29.677+0000] {processor.py:157} INFO - Started process (PID=2223) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:01:29.682+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:01:29.689+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:01:29.688+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:01:30.042+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:01:30.037+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:01:30.043+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:01:30.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.410 seconds
[2025-10-09T06:02:00.289+0000] {processor.py:157} INFO - Started process (PID=2287) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:02:00.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:02:00.294+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:02:00.293+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:02:00.511+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:02:00.509+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:02:00.512+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:02:00.528+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.241 seconds
[2025-10-09T06:02:30.898+0000] {processor.py:157} INFO - Started process (PID=2350) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:02:30.899+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:02:30.901+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:02:30.900+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:02:31.124+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:02:31.122+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:02:31.124+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:02:31.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.245 seconds
[2025-10-09T06:03:02.187+0000] {processor.py:157} INFO - Started process (PID=2421) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:03:02.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:03:02.190+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:03:02.189+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:03:02.402+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:03:02.400+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:03:02.403+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:03:02.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.234 seconds
[2025-10-09T06:03:32.540+0000] {processor.py:157} INFO - Started process (PID=2485) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:03:32.541+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:03:32.543+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:03:32.543+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:03:32.988+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:03:32.986+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:03:32.988+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:03:33.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.467 seconds
[2025-10-09T06:04:03.788+0000] {processor.py:157} INFO - Started process (PID=2549) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:04:03.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:04:03.798+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:04:03.798+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:04:04.146+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:04:04.137+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:04:04.146+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:04:04.169+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.386 seconds
[2025-10-09T06:04:34.786+0000] {processor.py:157} INFO - Started process (PID=2613) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:04:34.786+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:04:34.788+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:04:34.788+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:04:34.990+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:04:34.989+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:04:34.991+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:04:35.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.220 seconds
[2025-10-09T06:05:06.084+0000] {processor.py:157} INFO - Started process (PID=2677) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:05:06.085+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:05:06.087+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:05:06.087+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:05:06.351+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:05:06.349+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:05:06.351+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:05:06.371+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.290 seconds
[2025-10-09T06:05:36.568+0000] {processor.py:157} INFO - Started process (PID=2741) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:05:36.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:05:36.572+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:05:36.572+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:05:36.869+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:05:36.867+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:05:36.870+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:05:36.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.319 seconds
[2025-10-09T06:06:07.201+0000] {processor.py:157} INFO - Started process (PID=2805) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:06:07.202+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:06:07.204+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:06:07.203+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:06:07.434+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:06:07.433+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:06:07.435+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:06:07.451+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.252 seconds
[2025-10-09T06:06:38.272+0000] {processor.py:157} INFO - Started process (PID=2869) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:06:38.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:06:38.275+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:06:38.274+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:06:38.479+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:06:38.477+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:06:38.479+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:06:38.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.220 seconds
[2025-10-09T06:07:08.932+0000] {processor.py:157} INFO - Started process (PID=2933) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:07:08.936+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:07:08.938+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:07:08.938+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:07:09.139+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:07:09.138+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:07:09.140+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:07:09.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.221 seconds
[2025-10-09T06:07:40.233+0000] {processor.py:157} INFO - Started process (PID=2997) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:07:40.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:07:40.235+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:07:40.234+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:07:40.447+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:07:40.445+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:07:40.447+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:07:40.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.232 seconds
[2025-10-09T06:08:10.582+0000] {processor.py:157} INFO - Started process (PID=3061) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:08:10.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:08:10.584+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:08:10.584+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:08:10.789+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:08:10.787+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:08:10.790+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:08:10.804+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.224 seconds
[2025-10-09T06:08:40.898+0000] {processor.py:157} INFO - Started process (PID=3125) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:08:40.898+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:08:40.900+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:08:40.900+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:08:41.110+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:08:41.109+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:08:41.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:08:41.123+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.228 seconds
[2025-10-09T06:09:12.221+0000] {processor.py:157} INFO - Started process (PID=3189) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:09:12.222+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:09:12.223+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:09:12.223+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:09:12.542+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:09:12.541+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:09:12.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:09:12.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.336 seconds
[2025-10-09T06:09:42.741+0000] {processor.py:157} INFO - Started process (PID=3253) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:09:42.741+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:09:42.743+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:09:42.743+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:09:42.983+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:09:42.981+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:09:42.983+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:09:42.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.260 seconds
[2025-10-09T06:10:13.325+0000] {processor.py:157} INFO - Started process (PID=3317) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:10:13.327+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:10:13.329+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:10:13.329+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:10:13.613+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:10:13.611+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:10:13.613+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:10:13.626+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.305 seconds
[2025-10-09T06:10:43.712+0000] {processor.py:157} INFO - Started process (PID=3381) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:10:43.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:10:43.714+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:10:43.714+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:10:43.915+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:10:43.913+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:10:43.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:10:43.926+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.216 seconds
[2025-10-09T06:11:14.225+0000] {processor.py:157} INFO - Started process (PID=3445) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:11:14.226+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:11:14.228+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:11:14.228+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:11:14.579+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:11:14.577+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:11:14.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:11:14.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.367 seconds
[2025-10-09T06:11:44.696+0000] {processor.py:157} INFO - Started process (PID=3509) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:11:44.697+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:11:44.698+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:11:44.698+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:11:44.907+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:11:44.905+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:11:44.907+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:11:45.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.319 seconds
[2025-10-09T06:27:58.641+0000] {processor.py:157} INFO - Started process (PID=3573) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:27:58.642+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:27:58.645+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:27:58.644+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:27:58.903+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:27:58.901+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:27:58.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:27:58.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.282 seconds
[2025-10-09T06:35:27.970+0000] {processor.py:157} INFO - Started process (PID=3637) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:35:27.971+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:35:27.973+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:35:27.973+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:35:28.379+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:35:28.376+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:35:28.380+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:35:28.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.429 seconds
[2025-10-09T06:59:39.930+0000] {processor.py:157} INFO - Started process (PID=3701) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T06:59:39.932+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T06:59:39.937+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:59:39.936+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:59:40.806+0000] {logging_mixin.py:151} INFO - [2025-10-09T06:59:40.802+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T06:59:40.806+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T06:59:40.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.899 seconds
[2025-10-09T07:16:10.584+0000] {processor.py:157} INFO - Started process (PID=3765) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:16:10.585+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:16:10.588+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:16:10.588+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:16:11.055+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:16:11.054+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:16:11.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:16:11.067+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.487 seconds
[2025-10-09T07:16:41.755+0000] {processor.py:157} INFO - Started process (PID=3829) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:16:41.756+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:16:41.757+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:16:41.757+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:16:42.076+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:16:42.075+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:16:42.076+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:16:42.087+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.336 seconds
[2025-10-09T07:17:48.413+0000] {processor.py:157} INFO - Started process (PID=3893) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:17:48.413+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:17:48.416+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:17:48.415+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:17:49.110+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:17:49.109+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:17:49.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:17:49.127+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.717 seconds
[2025-10-09T07:18:19.911+0000] {processor.py:157} INFO - Started process (PID=3957) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:18:19.913+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:18:19.916+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:18:19.916+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:18:20.229+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:18:20.227+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:18:20.231+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:18:20.243+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.335 seconds
[2025-10-09T07:19:20.180+0000] {processor.py:157} INFO - Started process (PID=4021) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:19:20.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:19:20.182+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:19:20.182+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:19:20.481+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:19:20.479+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:19:20.481+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:19:20.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.313 seconds
[2025-10-09T07:21:37.818+0000] {processor.py:157} INFO - Started process (PID=4085) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:21:37.820+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:21:37.822+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:21:37.822+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:21:38.163+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:21:38.160+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:21:38.164+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:21:38.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.365 seconds
[2025-10-09T07:22:22.576+0000] {processor.py:157} INFO - Started process (PID=4149) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:22:22.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:22:22.580+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:22:22.579+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:22:22.901+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:22:22.898+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:22:22.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:22:22.916+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.343 seconds
[2025-10-09T07:23:11.196+0000] {processor.py:157} INFO - Started process (PID=4213) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:23:11.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:23:11.198+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:23:11.198+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:23:11.515+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:23:11.513+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:23:11.515+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:23:11.527+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.334 seconds
[2025-10-09T07:24:31.428+0000] {processor.py:157} INFO - Started process (PID=4277) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:24:31.428+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:24:31.430+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:24:31.429+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:24:31.727+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:24:31.726+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:24:31.728+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:24:31.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.315 seconds
[2025-10-09T07:25:03.693+0000] {processor.py:157} INFO - Started process (PID=4341) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:25:03.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:25:03.699+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:25:03.698+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:25:04.013+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:25:04.012+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:25:04.013+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:25:04.027+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.337 seconds
[2025-10-09T07:25:34.541+0000] {processor.py:157} INFO - Started process (PID=4405) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:25:34.541+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:25:34.543+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:25:34.543+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:25:34.862+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:25:34.860+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:25:34.865+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:25:34.876+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.338 seconds
[2025-10-09T07:27:18.945+0000] {processor.py:157} INFO - Started process (PID=4469) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:27:18.946+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:27:18.947+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:27:18.947+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:27:19.248+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:27:19.247+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:27:19.248+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:27:19.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.321 seconds
[2025-10-09T07:28:32.260+0000] {processor.py:157} INFO - Started process (PID=4533) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:28:32.264+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:28:32.270+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:28:32.269+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:28:32.964+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:28:32.960+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:28:32.968+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:28:32.989+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.733 seconds
[2025-10-09T07:29:18.108+0000] {processor.py:157} INFO - Started process (PID=4597) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:29:18.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:29:18.111+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:29:18.111+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:29:18.453+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:29:18.449+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:29:18.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:29:18.470+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.364 seconds
[2025-10-09T07:30:34.221+0000] {processor.py:157} INFO - Started process (PID=4661) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:30:34.222+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:30:34.224+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:30:34.224+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:30:34.556+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:30:34.554+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:30:34.557+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:30:34.569+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.350 seconds
[2025-10-09T07:32:34.863+0000] {processor.py:157} INFO - Started process (PID=4725) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:32:34.864+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:32:34.866+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:32:34.865+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:32:35.172+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:32:35.171+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:32:35.174+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:32:35.186+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.325 seconds
[2025-10-09T07:33:06.576+0000] {processor.py:157} INFO - Started process (PID=4789) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:33:06.579+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:33:06.581+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:33:06.581+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:33:06.890+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:33:06.887+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:33:06.890+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:33:06.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.328 seconds
[2025-10-09T07:34:35.932+0000] {processor.py:157} INFO - Started process (PID=4853) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:34:35.933+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:34:35.934+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:34:35.934+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:34:36.355+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:34:36.352+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:34:36.355+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:34:36.368+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.438 seconds
[2025-10-09T07:35:08.184+0000] {processor.py:157} INFO - Started process (PID=4917) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T07:35:08.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T07:35:08.187+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:35:08.186+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:35:08.608+0000] {logging_mixin.py:151} INFO - [2025-10-09T07:35:08.606+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T07:35:08.609+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T07:35:08.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.438 seconds
[2025-10-09T08:05:49.045+0000] {processor.py:157} INFO - Started process (PID=4981) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T08:05:49.046+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T08:05:49.051+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:05:49.051+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T08:05:49.424+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:05:49.423+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T08:05:49.424+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T08:05:49.437+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.397 seconds
[2025-10-09T08:30:30.704+0000] {processor.py:157} INFO - Started process (PID=5045) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T08:30:30.708+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T08:30:30.713+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:30:30.713+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T08:30:31.070+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:30:31.065+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T08:30:31.072+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T08:30:31.088+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.386 seconds
[2025-10-09T08:46:52.760+0000] {processor.py:157} INFO - Started process (PID=5109) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T08:46:52.762+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T08:46:52.764+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:46:52.763+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T08:46:53.498+0000] {logging_mixin.py:151} INFO - [2025-10-09T08:46:53.494+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T08:46:53.499+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T08:46:53.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.764 seconds
[2025-10-09T09:57:04.758+0000] {processor.py:157} INFO - Started process (PID=5173) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T09:57:04.762+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T09:57:04.765+0000] {logging_mixin.py:151} INFO - [2025-10-09T09:57:04.765+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T09:57:05.226+0000] {logging_mixin.py:151} INFO - [2025-10-09T09:57:05.219+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T09:57:05.227+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T09:57:05.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.496 seconds
[2025-10-09T11:25:22.796+0000] {processor.py:157} INFO - Started process (PID=5237) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T11:25:22.800+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T11:25:22.802+0000] {logging_mixin.py:151} INFO - [2025-10-09T11:25:22.802+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T11:25:23.153+0000] {logging_mixin.py:151} INFO - [2025-10-09T11:25:23.152+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T11:25:23.155+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T11:25:23.168+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.375 seconds
[2025-10-09T12:36:33.490+0000] {processor.py:157} INFO - Started process (PID=5301) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T12:36:33.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T12:36:33.496+0000] {logging_mixin.py:151} INFO - [2025-10-09T12:36:33.495+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T12:36:33.863+0000] {logging_mixin.py:151} INFO - [2025-10-09T12:36:33.861+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T12:36:33.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T12:36:33.874+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.389 seconds
[2025-10-09T12:37:04.714+0000] {processor.py:157} INFO - Started process (PID=5365) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T12:37:04.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T12:37:04.717+0000] {logging_mixin.py:151} INFO - [2025-10-09T12:37:04.717+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T12:37:05.016+0000] {logging_mixin.py:151} INFO - [2025-10-09T12:37:05.015+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T12:37:05.016+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T12:37:05.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.317 seconds
[2025-10-09T14:05:27.338+0000] {processor.py:157} INFO - Started process (PID=5429) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T14:05:27.339+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T14:05:27.342+0000] {logging_mixin.py:151} INFO - [2025-10-09T14:05:27.341+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T14:05:27.682+0000] {logging_mixin.py:151} INFO - [2025-10-09T14:05:27.679+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T14:05:27.682+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T14:05:27.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.365 seconds
[2025-10-09T14:24:35.353+0000] {processor.py:157} INFO - Started process (PID=5493) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T14:24:35.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T14:24:35.365+0000] {logging_mixin.py:151} INFO - [2025-10-09T14:24:35.365+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T14:24:36.499+0000] {logging_mixin.py:151} INFO - [2025-10-09T14:24:36.496+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T14:24:36.500+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T14:24:36.524+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 1.185 seconds
[2025-10-09T15:06:47.821+0000] {processor.py:157} INFO - Started process (PID=5557) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T15:06:47.825+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T15:06:47.829+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:06:47.829+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:06:48.685+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:06:48.682+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:06:48.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:06:48.709+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.895 seconds
[2025-10-09T15:49:11.532+0000] {processor.py:157} INFO - Started process (PID=5621) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T15:49:11.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T15:49:11.535+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:49:11.535+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:49:11.884+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:49:11.882+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:49:11.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:49:11.898+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.368 seconds
[2025-10-09T15:49:42.510+0000] {processor.py:157} INFO - Started process (PID=5685) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T15:49:42.514+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T15:49:42.516+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:49:42.515+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:49:42.824+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:49:42.823+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:49:42.825+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:49:42.836+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.329 seconds
[2025-10-09T15:50:12.932+0000] {processor.py:157} INFO - Started process (PID=5749) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T15:50:12.932+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T15:50:12.935+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:50:12.934+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:50:13.240+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:50:13.239+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:50:13.240+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:50:13.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.322 seconds
[2025-10-09T15:50:43.317+0000] {processor.py:157} INFO - Started process (PID=5812) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T15:50:43.318+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T15:50:43.319+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:50:43.319+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:50:43.626+0000] {logging_mixin.py:151} INFO - [2025-10-09T15:50:43.625+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T15:50:43.627+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T15:50:43.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.323 seconds
[2025-10-09T16:07:42.010+0000] {processor.py:157} INFO - Started process (PID=5877) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T16:07:42.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T16:07:42.015+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:07:42.015+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:07:42.404+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:07:42.402+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:07:42.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:07:42.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.412 seconds
[2025-10-09T16:19:54.297+0000] {processor.py:157} INFO - Started process (PID=5941) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T16:19:54.298+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T16:19:54.299+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:19:54.299+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:19:54.703+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:19:54.694+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:19:54.704+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:19:54.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.437 seconds
[2025-10-09T16:20:25.842+0000] {processor.py:157} INFO - Started process (PID=6005) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T16:20:25.844+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T16:20:25.849+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:20:25.848+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:20:26.222+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:20:26.220+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:20:26.223+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:20:26.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.404 seconds
[2025-10-09T16:20:56.827+0000] {processor.py:157} INFO - Started process (PID=6069) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T16:20:56.827+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T16:20:56.829+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:20:56.829+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:20:57.140+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:20:57.139+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:20:57.141+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:20:57.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.328 seconds
[2025-10-09T16:21:28.742+0000] {processor.py:157} INFO - Started process (PID=6133) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T16:21:28.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T16:21:28.749+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:21:28.748+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:21:29.332+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:21:29.328+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:21:29.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:21:29.362+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.623 seconds
[2025-10-09T16:22:00.369+0000] {processor.py:157} INFO - Started process (PID=6197) to work on /opt/airflow/dags/src/train_model.py
[2025-10-09T16:22:00.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/src/train_model.py for tasks to queue
[2025-10-09T16:22:00.372+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:22:00.371+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:22:00.738+0000] {logging_mixin.py:151} INFO - [2025-10-09T16:22:00.737+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/src/train_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/train_model.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2025-10-09T16:22:00.738+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/src/train_model.py
[2025-10-09T16:22:00.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/src/train_model.py took 0.383 seconds
